spring:
    application:
        name: user-center-base
    datasource:
        url: jdbc:mysql://localhost:3306/user_center_base?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=utf8
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password: 123456
server:
    port: 8080

